// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _288Group.ECommerceShop.Persistence.Database;

namespace _288Group.ECommerceShop.Persistance.Migrations
{
    [DbContext(typeof(ECommerceShopContext))]
    [Migration("20210531211910_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("_288Group.ECommerceShop.Persistence.Model.DiscountCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DiscountCodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "EverythingIsAwesome",
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(3041),
                            DiscountPercentage = 20
                        });
                });

            modelBuilder.Entity("_288Group.ECommerceShop.Persistence.Model.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InnerExceptionMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("_288Group.ECommerceShop.Persistence.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 776, DateTimeKind.Utc).AddTicks(1210),
                            Name = "Wooden Spoon",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 2L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 777, DateTimeKind.Utc).AddTicks(9800),
                            Name = "Dax Cobra",
                            Price = 28500m
                        },
                        new
                        {
                            Id = 3L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(215),
                            Name = "Sunglasses",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 4L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(236),
                            Name = "Kite",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 5L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(249),
                            Name = "LEGO 75257 Star Wars Millennium Falcon",
                            Price = 112.5m
                        });
                });

            modelBuilder.Entity("_288Group.ECommerceShop.Persistence.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(1509),
                            Password = "ABC",
                            Username = "Fred"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreatedUtc = new DateTime(2021, 5, 31, 21, 19, 9, 778, DateTimeKind.Utc).AddTicks(1755),
                            Password = "ABC",
                            Username = "James"
                        });
                });

            modelBuilder.Entity("_288Group.ECommerceShop.Persistence.Model.UserProductBasket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
